export const COMMENT_ADD = 'COMMENT_ADD';
export const COMMENT_EDIT = 'COMMENT_EDIT';
export const COMMENT_DELETE = 'COMMENT_DELETE';
export const COMMENT_UPVOTE = 'COMMENT_UPVOTE';
export const COMMENT_DOWNVOTE = 'COMMENT_DOWNVOTE';